# Generated by Django 5.2 on 2025-04-14 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAppiBirthday', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billets',
            name='nom',
        ),
    ]
