# Generated by Django 5.2 on 2025-04-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppiBirthday', '0002_remove_billets_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='billets',
            name='nom',
            field=models.CharField(default='nom', max_length=100),
        ),
    ]
