# Generated by Django 5.2 on 2025-04-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppiBirthday', '0003_billets_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billets',
            name='nom',
            field=models.CharField(default="nom de l'invité", max_length=100),
        ),
    ]
