# Generated by Django 5.2 on 2025-04-16 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppiBirthday', '0004_alter_billets_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billets',
            name='nom',
            field=models.CharField(default="nom de l'invité", max_length=25),
        ),
        migrations.AlterField(
            model_name='billets',
            name='num_billet',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='invites',
            name='age',
            field=models.IntegerField(default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='invites',
            name='telephone',
            field=models.CharField(max_length=12),
        ),
    ]
