# Generated by Django 5.2 on 2025-04-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppiBirthday', '0006_alter_invites_adresse_alter_invites_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='adresse',
            field=models.CharField(default='mon quartier', max_length=50),
        ),
        migrations.AddField(
            model_name='admin',
            name='age',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='admin',
            name='email',
            field=models.EmailField(default='exemple@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='admin',
            name='nom',
            field=models.CharField(default="nom de l'administrateur", max_length=25),
        ),
        migrations.AddField(
            model_name='admin',
            name='prenom',
            field=models.CharField(default="prenom de l'administrateur", max_length=25),
        ),
        migrations.AddField(
            model_name='admin',
            name='sexe',
            field=models.CharField(default='masculin', max_length=10),
        ),
        migrations.AddField(
            model_name='admin',
            name='telephone',
            field=models.CharField(default='1234567890', max_length=12),
        ),
        migrations.AlterField(
            model_name='invites',
            name='age',
            field=models.IntegerField(default=1),
        ),
    ]
