# Generated by Django 5.2 on 2025-04-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppiBirthday', '0007_admin_adresse_admin_age_admin_email_admin_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invites',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='invites',
            name='telephone',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
