# Generated by Django 5.2 on 2025-04-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppiBirthday', '0008_alter_invites_email_alter_invites_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='mot_de_passe',
            field=models.CharField(default='1234567890', max_length=12),
        ),
    ]
