# Generated by Django 5.2 on 2025-04-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppiBirthday', '0009_admin_mot_de_passe'),
    ]

    operations = [
        migrations.AddField(
            model_name='billets',
            name='prenom',
            field=models.CharField(default="prenom de l'invité", max_length=15),
        ),
    ]
